### ISSUE TITLE
Telnet

### ISSUE THREAD

**Issue by eerison** [KostasEreksonas/Besder-6024PB-XMA501-ip-camera-security-investigation#3]
Really good doc thank you for this 

do you know how to access this camera via telnel?
other thing do you have any idea how to control the lead on the front? maybe some ptz command?

**Comment by KostasEreksonas** [comment]
Thank you.

The telnet port on the camera is closed and I haven't found a way to control the device through the port.

As for the front lead - I'm not really sure on how to control it.

I might take a look at these issues when I'll have some more free time.

**Comment by eerison** [comment]
Hey @KostasEreksonas for reply.

I could handle lights using camera's configuration 

https://github.com/dbuezas/icsee-ptz/issues/6

Thanks 😊
